# Generated by Django 2.0.1 on 2018-02-09 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeApp', '0005_auto_20180208_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='profile_image',
            field=models.ImageField(default='/static/images/user.png', upload_to='profile/'),
        ),
    ]
