# Generated by Django 2.0.1 on 2018-02-11 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeApp', '0006_auto_20180209_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='user_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experience',
            name='user_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='language',
            name='user_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reference',
            name='user_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skill',
            name='user_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
