# Generated by Django 2.0.1 on 2018-04-03 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeApp', '0008_major_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='level',
            field=models.CharField(choices=[('hs', 'Hight School'), ('un', 'Undergraduate'), ('ms', 'Master'), ('dr', 'Doctorate')], default='un', max_length=2),
        ),
    ]
