# Generated by Django 2.0.1 on 2018-01-28 10:47

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_no', models.CharField(max_length=10)),
                ('village_building', models.CharField(blank=True, max_length=64, null=True)),
                ('village_no', models.CharField(max_length=3)),
                ('alley', models.CharField(blank=True, max_length=20, null=True)),
                ('road', models.CharField(blank=True, max_length=20, null=True)),
                ('sub_area', models.CharField(max_length=20)),
                ('area', models.CharField(max_length=20)),
                ('province', models.CharField(max_length=20)),
                ('postcode', models.CharField(max_length=5)),
                ('pub_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academy_name', models.CharField(max_length=64)),
                ('level', models.CharField(choices=[('el', 'Elementary'), ('se', 'Secondary'), ('un', 'Undergraduate'), ('ms', 'Master'), ('dr', 'Doctorate')], default='un', max_length=2)),
                ('time_period', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=32)),
                ('position', models.CharField(max_length=32)),
                ('role', models.TextField(blank=True, max_length=400)),
                ('time_period', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('level', models.CharField(choices=[('b', 'Beginner'), ('e', 'Elementary'), ('i', 'Intermediate'), ('a', 'Advanced'), ('p', 'Proficiency')], default='b', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=128)),
                ('person_name', models.CharField(max_length=64)),
                ('contents', models.TextField(max_length=5000)),
                ('date', models.CharField(default='-/-/-', max_length=32)),
                ('time_period', models.CharField(default='xx/xx - yy/yy', max_length=32)),
                ('pub_date', models.DateTimeField(auto_now=True)),
                ('attachment', models.ManyToManyField(blank=True, related_name='student_attachment', to='resumeApp.Attachment')),
            ],
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major_name', models.CharField(max_length=64)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resumeApp.Branch')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resumeApp.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advisor_name', models.CharField(max_length=32)),
                ('position', models.CharField(max_length=32)),
                ('affiliation', models.CharField(max_length=64)),
                ('phone_no', models.CharField(max_length=10)),
                ('email', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), default=[], size=2)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('level', models.CharField(choices=[('b', 'Beginner'), ('e', 'Elementary'), ('i', 'Intermediate'), ('a', 'Advanced'), ('p', 'Proficiency')], default='b', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('phone_no', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), size=2)),
                ('email', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32), size=2)),
                ('birthday', models.CharField(max_length=10)),
                ('nationality', models.CharField(max_length=16)),
                ('religion', models.CharField(max_length=16)),
                ('age', models.IntegerField(default=0)),
                ('activity', models.TextField(max_length=500)),
                ('hobbie', models.TextField(max_length=500)),
                ('pub_date', models.DateTimeField(auto_now=True)),
                ('address', models.ManyToManyField(related_name='student_address', to='resumeApp.Address')),
                ('education', models.ManyToManyField(related_name='student_education', to='resumeApp.Education')),
                ('experience', models.ManyToManyField(related_name='student_experience', to='resumeApp.Experience')),
                ('language', models.ManyToManyField(related_name='student_language', to='resumeApp.Language')),
                ('letter', models.ManyToManyField(blank=True, related_name='student_letter', to='resumeApp.Letter')),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resumeApp.Reference')),
                ('skill', models.ManyToManyField(related_name='student_skill', to='resumeApp.Skill')),
            ],
        ),
        migrations.AddField(
            model_name='letter',
            name='major',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resumeApp.Major'),
        ),
        migrations.AddField(
            model_name='education',
            name='major',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resumeApp.Major'),
        ),
    ]
