# Generated by Django 2.0.1 on 2018-01-31 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='language',
            field=models.CharField(choices=[('TH', 'Thai'), ('EN', 'English')], default='TH', max_length=2),
        ),
    ]
