# Generated by Django 2.0.1 on 2018-01-25 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='village_building',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
