# Generated by Django 2.0.1 on 2018-02-01 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeApp', '0002_letter_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='language',
            field=models.CharField(choices=[('th', 'Thai'), ('en', 'English')], default='TH', max_length=2),
        ),
    ]
