# Generated by Django 2.0.1 on 2018-01-27 11:21

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resumeApp', '0002_letter_major'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='contents',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(max_length=500), default=[], size=10),
        ),
        migrations.AlterField(
            model_name='letter',
            name='major',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resumeApp.Major'),
        ),
    ]
