# Generated by Django 2.0.1 on 2018-01-30 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeApp', '0002_auto_20180128_1056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='first_name',
            new_name='first_name_en',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='last_name',
            new_name='last_name_en',
        ),
        migrations.RemoveField(
            model_name='student',
            name='address',
        ),
        migrations.AddField(
            model_name='student',
            name='address_en',
            field=models.ManyToManyField(related_name='student_address_en', to='resumeApp.Address'),
        ),
        migrations.AddField(
            model_name='student',
            name='address_th',
            field=models.ManyToManyField(related_name='student_address_th', to='resumeApp.Address'),
        ),
        migrations.AddField(
            model_name='student',
            name='first_name_th',
            field=models.CharField(default='-', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='last_name_th',
            field=models.CharField(default='-', max_length=32),
            preserve_default=False,
        ),
    ]
