# Generated by Django 2.0.1 on 2018-02-08 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeApp', '0002_auto_20180208_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
