# Generated by Django 2.0.1 on 2018-01-25 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeApp', '0002_address_village_building'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='level',
            field=models.CharField(choices=[('b', 'Beginner'), ('e', 'Elementary'), ('i', 'Intermediate'), ('a', 'Advanced'), ('p', 'Proficiency')], default='b', max_length=1),
        ),
    ]
