# Generated by Django 2.0.1 on 2018-01-23 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumeApp', '0002_letter_attachments2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='letter',
            name='attachments2',
        ),
    ]
