# Generated by Django 2.0.1 on 2018-02-01 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeApp', '0003_auto_20180201_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='letter',
            name='person_name',
        ),
        migrations.AddField(
            model_name='letter',
            name='position',
            field=models.CharField(choices=[('dr', 'ผู้อำนวยการ'), ('hr', 'ผู้จัดการทรัพยากรบุคคล'), ('ot', 'อื่นๆ')], default='hr', max_length=64),
        ),
        migrations.AddField(
            model_name='letter',
            name='position_other',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
