# Generated by Django 2.0.1 on 2018-01-30 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeApp', '0003_auto_20180130_1208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='address_en',
        ),
        migrations.AddField(
            model_name='student',
            name='address_en',
            field=models.TextField(default='-', max_length=640),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='student',
            name='address_th',
        ),
        migrations.AddField(
            model_name='student',
            name='address_th',
            field=models.TextField(default='-', max_length=640),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
