# Generated by Django 2.0.1 on 2018-01-27 11:25

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeApp', '0003_auto_20180127_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='letter',
            name='company_name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='letter',
            name='contents',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(max_length=1400), default=[], size=10),
        ),
        migrations.AlterField(
            model_name='letter',
            name='person_name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='letter',
            name='time_period',
            field=models.CharField(default='xx/xx - yy/yy', max_length=32),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=64),
        ),
    ]
