# Generated by Django 2.0.1 on 2018-01-25 17:29

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeApp', '0004_auto_20180125_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32), size=2),
        ),
    ]
