# Generated by Django 2.0.1 on 2018-01-30 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumeApp', '0004_auto_20180130_1308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='hobbie',
            new_name='hobby',
        ),
    ]
