# Generated by Django 2.0.1 on 2018-02-01 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeApp', '0004_auto_20180201_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='position',
            field=models.CharField(choices=[('dr', 'ผู้อำนวยการ'), ('hr', 'ผู้จัดการฝ่ายทรัพยากรบุคคล'), ('ot', 'อื่นๆ โปรดระบุ')], default='hr', max_length=64),
        ),
    ]
