# Generated by Django 2.0.1 on 2018-01-24 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeApp', '0004_auto_20180123_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='pub_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='letter',
            name='pub_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='student',
            name='pub_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
