# Generated by Django 2.0.1 on 2018-01-27 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeApp', '0004_auto_20180127_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='letter',
            field=models.ManyToManyField(blank=True, related_name='student_letter', to='resumeApp.Letter'),
        ),
    ]
