# Generated by Django 2.0.1 on 2018-01-30 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeApp', '0005_auto_20180130_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('m', 'Male'), ('f', 'Female')], default='m', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='birthday',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='religion',
            field=models.CharField(blank=True, choices=[('b', 'Buddistsm'), ('c', 'Christians'), ('h', 'Hinduism')], max_length=16, null=True),
        ),
    ]
