# Generated by Django 2.0.1 on 2018-01-28 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeApp', '0005_auto_20180127_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='activity',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='student',
            name='hobbie',
            field=models.TextField(max_length=500),
        ),
    ]
