# Generated by Django 2.0.1 on 2018-01-26 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeApp', '0005_auto_20180125_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='role',
            field=models.TextField(blank=True, max_length=400),
        ),
    ]
