# Generated by Django 2.0.1 on 2018-02-11 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeApp', '0007_auto_20180212_0058'),
    ]

    operations = [
        migrations.AddField(
            model_name='major',
            name='user_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
