# Generated by Django 2.0.1 on 2018-01-26 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeApp', '0007_auto_20180126_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='level',
            field=models.CharField(choices=[('20', 'Beginner'), ('40', 'Elementary'), ('60', 'Intermediate'), ('80', 'Advanced'), ('100', 'Proficiency')], default='20', max_length=3),
        ),
    ]
