# Generated by Django 2.0.1 on 2018-01-26 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeApp', '0008_auto_20180126_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='level',
            field=models.CharField(choices=[('b', 'Beginner'), ('e', 'Elementary'), ('i', 'Intermediate'), ('a', 'Advanced'), ('p', 'Proficiency')], default='b', max_length=1),
        ),
    ]
